aws:
  cloudwatch:
    metrics_namespace: ChineseProduceForecast
  region: us-east-1
  s3:
    bucket_name: ml-monitoring-bucket
monitoring:
  alerts:
    cooldown_minutes: 30
    enabled: true
    local_mode: true
  performance:
    cpu_threshold: 80
    disk_threshold: 90
    drift_threshold: 0.25
    memory_threshold: 85
    performance_degradation_threshold: 0.15
project:
  name: chinese-produce-forecasting
  version: 1.2.0
