aws:
  account_id: '346761359662'
  cloudwatch:
    log_group: /aws/sagemaker/chinese-produce-forecast
    metrics_namespace: ChineseProduceForecast
  region: us-east-1
  s3:
    artifacts_prefix: artifacts/
    bucket_name: sagemaker-us-east-1-346761359662
    data_prefix: data/
    logs_prefix: logs/
    model_prefix: models/
  sagemaker:
    endpoint_config:
      auto_scaling:
        max_capacity: 10
        min_capacity: 1
        target_value: 70.0
      initial_instance_count: 1
      instance_type: ml.t2.medium
      variant_weight: 1
    execution_role: arn:aws:iam::346761359662:role/service-role/AmazonSageMaker-ExecutionRole-20250511T063988
    instance_count: 1
    instance_type_inference: ml.t2.medium
    instance_type_training: ml.m5.xlarge
    max_runtime_seconds: 86400
    model_package_group_name: chinese-produce-forecasting-models
cost_optimization:
  scheduled_scaling:
    enabled: true
    scale_down_cron: 0 18 * * *
    scale_up_cron: 0 8 * * *
    timezone: Asia/Shanghai
  spot_instances:
    enabled: false
    max_price: '0.50'
data:
  processed_files:
    features: data/processed/features.parquet
    test: data/processed/test.parquet
    train: data/processed/train.parquet
    validation: data/processed/validation.parquet
  raw_files:
    item_master: data/raw/annex1.csv
    loss_rates: data/raw/annex4.csv
    sales_transactions: data/raw/annex2.csv
    wholesale_prices: data/raw/annex3.csv
  validation:
    date_range:
      end: '2024-12-31'
      start: '2020-01-01'
    max_missing_percentage: 0.1
    min_data_points: 100
deployment:
  blue_green:
    enabled: true
    evaluation_period: 300
    traffic_shift_percentage: 10
  environments:
    dev:
      auto_scaling_enabled: false
      instance_type: ml.t2.medium
    prod:
      auto_scaling_enabled: true
      instance_type: ml.m5.xlarge
      max_capacity: 10
      min_capacity: 2
    staging:
      auto_scaling_enabled: true
      instance_type: ml.m5.large
      max_capacity: 3
      min_capacity: 1
  rollback:
    auto_rollback_enabled: true
    performance_threshold: 0.2
evaluation:
  forecast_horizons:
  - 1
  - 7
  - 14
  - 30
  metrics:
  - mae
  - mse
  - rmse
  - mape
  - smape
  - r2
  thresholds:
    mape_threshold: 15.0
    r2_threshold: 0.7
    rmse_threshold: 5.0
features:
  external:
    exchange_rate: true
    holidays: true
    weather: false
  price:
    moving_averages:
    - 7
    - 14
    - 30
    percentage_change: true
    price_ratios: true
    volatility_windows:
    - 7
    - 14
    - 30
  temporal:
    lag_features:
    - 1
    - 7
    - 14
    - 30
    seasonality:
      daily: false
      monthly: true
      weekly: true
      yearly: true
    window_sizes:
    - 7
    - 14
    - 30
    - 90
logging:
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  handlers:
  - console
  - file
  - cloudwatch
  level: INFO
models:
  ensemble:
    method: weighted_average
    weights: auto
  hyperparameter_tuning:
    max_jobs: 20
    max_parallel_jobs: 4
    method: bayesian
    objective_metric: validation:mape
  neural_networks:
    gru:
      batch_size: 32
      dropout: 0.2
      epochs: 100
      hidden_units:
      - 64
      - 32
      learning_rate: 0.001
    lstm:
      batch_size: 32
      dropout: 0.2
      epochs: 100
      hidden_units:
      - 64
      - 32
      learning_rate: 0.001
    transformer:
      batch_size: 32
      d_model: 64
      dropout: 0.1
      epochs: 100
      n_heads: 8
      num_layers: 4
  statistical:
    arima:
      max_d: 2
      max_p: 5
      max_q: 5
      seasonal: true
    prophet:
      daily_seasonality: false
      seasonality_mode: additive
      weekly_seasonality: true
      yearly_seasonality: true
monitoring:
  alerts:
    email: btiduwarlambodhar@sandiego.edu
    slack_webhook: null
    sns_topic: arn:aws:sns:us-east-1:346761359662:produce-forecast-alerts
  data_quality:
    missing_data_threshold: 0.05
    outlier_threshold: 3.0
    schema_validation: true
  performance:
    drift_threshold: 0.1
    monitoring_window: 7
    performance_degradation_threshold: 0.15
project:
  author: Bhupal Lambodhar
  description: MLOps pipeline for Chinese produce market RMB forecasting
  email: btiduwarlambodhar@sandiego.edu
  name: chinese-produce-forecast
  repository: https://github.com/btlambodh/demand-stock-forecasting-mlops.git
  version: 1.0.0
security:
  encryption:
    kms_key_id: null
    s3_encryption: AES256
  vpc:
    enabled: false
    security_group_ids: []
    subnet_ids: []
    vpc_id: null
testing:
  integration_tests:
    data_quality_tests: true
    endpoint_tests: true
    model_performance_tests: true
  load_testing:
    duration_minutes: 10
    max_requests_per_second: 100
  unit_tests:
    coverage_threshold: 80
training:
  cross_validation:
    method: time_series_split
    n_splits: 5
    test_size: 30
  early_stopping:
    min_delta: 0.001
    patience: 10
    restore_best_weights: true
  test_ratio: 0.15
  train_ratio: 0.7
  validation_ratio: 0.15
